import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import Footer from "./_components/footer";


const raleway = Raleway({
  variable: "--font-raleway-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Stepozo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
